#!/bin/sh

doit () {
   echo "
	Running: $@"
   eval "$@" || {
      echo "Error: command [$@] failed with status $?

Please try running this again before giving up.  For some unknown reason, a
second pass sometimes helps."
      exit 1
   }
}

doit rm -f config.cache Makefile.in aclocal.m4 config.h.in configure test/Makefile.in test/Maketests
doit rm -rf autom4te.cache

echo "N.B. This script should eventually be replaced by using 'autoreconf -i'"

doit touch Makefile.am configure.ac
doit autopoint
doit aclocal -I m4
doit libtoolize -c
doit autoheader
doit autoconf
doit automake --gnu --add-missing --copy
echo "
Congratulations.  All the auto* commands completed successfully."
