#!/bin/sh

rm -f config.cache Makefile.in aclocal.m4 config.h.in configure test/Makefile.in test/Maketests
rm -rf autom4te.cache

echo "N.B. This script should eventually be replaced by using 'autoreconf -i'"

touch Makefile.am configure.ac
aclocal -I m4
libtoolize -c
autoheader
autoconf
automake --gnu --add-missing --copy
