BEGIN {
  MPFR_PRECISION = 10;
  pi     = mpfr_const_pi();
  euler  = mpfr_const_euler();
  print pi, euler
  print mpfr_add(pi, euler);
  print mpfr_sub(pi, euler);
  print mpfr_mul(pi, euler);
  print mpfr_div(pi, euler);
  print mpfr_pow(pi, euler);
  print mpfr_sqr(pi);
  print mpfr_sqrt(pi);
  print mpfr_neg(pi);
  print mpfr_abs(pi);
  print mpfr_log(pi);
  print mpfr_log2(pi);
  print mpfr_log10(pi);
  print mpfr_exp(pi);
  print mpfr_exp2(pi);
  print mpfr_exp10(pi);
  print mpfr_sin(euler);
  print mpfr_cos(euler);
  print mpfr_tan(euler);
  print mpfr_acos(euler);
  print mpfr_asin(euler);
  print mpfr_atan(euler);
  print mpfr_atan2(pi, euler);
  print mpfr_lngamma(pi);
  print mpfr_erfc(pi);
  print mpfr_gamma(pi);
  print mpfr_erf(pi);
  print mpfr_hypot(pi, euler);
  print mpfr_const_log2();
  print mpfr_rint(pi);
  print mpfr_ceil(pi);
  print mpfr_floor(pi);
  print mpfr_round(pi);
  print mpfr_trunc(pi);
  print mpfr_frac(pi);
  print mpfr_inp_str(pi, euler);
  print mpfr_out_str(pi, 10);
  print mpfr_min(pi, euler);
  print mpfr_max(pi, euler);
  print mpfr_cmp(pi, euler);
  print mpfr_cmpabs(pi, euler);
  print mpfr_nan_p(pi);
  print mpfr_inf_p(pi);
  print mpfr_number_p(pi);
  print mpfr_zero_p(pi);
  print mpfr_sgn(pi);
  print mpfr_greater_p(pi, euler);
  print mpfr_greaterequal_p(pi, euler);
  print mpfr_less_p(pi, euler);
  print mpfr_lessequal_p(pi, euler);
  print mpfr_lessgreater_p(pi, euler);
  print mpfr_equal_p(pi, euler);
  print mpfr_unordered_p(pi, euler);
  print mpfr_underflow_p();
  print mpfr_overflow_p();
  print mpfr_nanflag_p();
  print mpfr_inexflag_p();
  print mpfr_erangeflag_p();
}
