name: Merge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/merge-upstream@v1
        with:
          repository: git://git.code.sf.net/p/
          upstream: gawkextlib/code
